version: '3.9'
services:
  ecommerce_wsd_service:
    container_name: ecommerce_wsd_service_container
    build: ./
    image: ecommerce_wsd_service
    ports:
      - "8083:8083"
    depends_on:
      - postgresqldb
      - logstash
    environment:
      - FLYWAY_ENABLED=true
    entrypoint: ["java", "-jar", "/ecommerce-wsd.jar"]
  postgresqldb:
    image: postgres:13
    container_name: postgresdb_container
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=root
      - POSTGRES_DB=ecommerce_wsd
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: elasticsearch_container
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.1
    container_name: logstash_container
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5044:5044"
    depends_on:
      - elasticsearch
volumes:
  postgres_data:
    driver: local
