server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://postgresqldb:5432/ecommerce_wsd
    username: postgres
    password: root
    hikari:
      maximumPoolSize: 100
      connectionTimeout: 60000
      idleTimeout: 600000
      maxLifetime: 1800000
      minimumIdle: 2
      pool-name: EcommerceWsdServiceHikariCP
  jpa:
    hibernate:
      ddl-auto: update
