server:
  port: ${SERVER_PORT}

spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximumPoolSize: ${HIKARI_MAXIMUM_POOL_SIZE}
      connectionTimeout: 60000
      idleTimeout: 600000
      maxLifetime: 1800000
      minimumIdle: ${HIKARI_MAXIMUM_POOL_SIZE}
      pool-name: EcommerceWsdServiceHikariCP
      jpa:
        hibernate:
          ddl-auto: update
  flyway:
    url: ${DATASOURCE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    baselineOnMigrate: true
    enabled: ${FLYWAY_ENABLED:false}
    locations: classpath:db/migration

info:
  app:
    name: Ecommerce service
    description: This service is responsible for ecommerce operations.
    version: 1.0
    profile: release