server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_wsd
    username: postgres
    password: root
    hikari:
      maximumPoolSize: 100
      connectionTimeout: 60000
      idleTimeout: 600000
      maxLifetime: 1800000
      minimumIdle: 2
      pool-name: EcommerceWsdServiceHikariCP
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: ${FLYWAY_ENABLED:false}
    url: jdbc:postgresql://localhost:5432/ecommerce_wsd
    user: postgres
    password: root
    baselineOnMigrate: true
    locations: classpath:db/migration

info:
  app:
    name: Ecommerce service
    description: This service is responsible for ecommerce operations.
    version: 1.0
    profile: dev